---
title: "Emissions Analysis"
author: "Kristen Fedak"
date: "July 17, 2017"
output: html_document
---


```{r, echo=FALSE, warning=FALSE, message=FALSE, results='markup', cache=FALSE}
  library(tidyverse)
  library(knitr)
```

# Load and format data
```{r}
  emission_factors <- readRDS(file = "../r_files/emission_factors.RDS")
```

```{r}
  #1. set variable types from character -> factor
  #3. removes duplicate rows that were remnants of when real-time monitors had timestamps, so multiple rows per test even though the mass_ef was a single value for the test. 
  ef_bymass <- emission_factors %>%
              filter(qc != "bad") %>%
               dplyr::mutate(fuel = factor(fuel),
                      qc = factor(qc),
                      pol = factor(pol)) %>%
               dplyr::distinct()
```

# check amount of data is correct

* expect 25 pollutants x 
```{r}
table(ef_bymass$id)
```



# Summarize emissions factors by pollutant and fuel type
```{r}
ef_sum <- ef_bymass %>%
                    dplyr::group_by(fuel, pol) %>%
                    dplyr::summarize(nreps = n(),
                                     mean_ef = round(mean(mass_per_mass_fuel, na.rm = TRUE), 4),
                                     min_ef = round(min(mass_per_mass_fuel, na.rm = TRUE), 4),
                                     max_ef = round(max(mass_per_mass_fuel, na.rm = TRUE), 4))
#mass_ef in units g pol / kg fuel; one average value per fuel_type

ef_mean_table <- select(ef_sum, fuel, pol, mean_ef) %>%
                 spread(fuel, mean_ef) %>%
                 select(-background, -blank)
```

### Table 1. Mean emission factors (mass basis) for various startup materials and pollutants
* units = g pollutant emitted per kg of fuel burned
```{r echo = FALSE}
knitr::kable(ef_mean_table)
```

# Figure 1. Mean emission factors (mass basis) for various startup materials and pollutants

```{r}
  
```

